[package]
name = "parallel_test"
version = "0.1.0"
authors = ["Zsolt Krüpl <hg2ecz@ham.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rayon = "*"

[build-dependencies]
cc = "*"
